### ISSUE TITLE
Data protection

### ISSUE THREAD

**Issue by gilles-hemmerle** [epicshaggy/capacitor-native-biometric#35]
Hello,

I'd have a question regarding the security of the data stored in the device.

I noticed that the password is decrypted before you are prompted for the fingerprint. It means that the password is not safely secured, correct?

Is there any plan to encrypt the password with the biometric data in order not to be able to decrypt it without actually using your biometric data?

**Comment by ahoyahoy** [comment]
+1

**Comment by gbkwiatt** [comment]
I have just notice that too. What's the point of biometric check if you can get credentials without it ?

**Comment by epicshaggy** [comment]
Hi! 

This is true for the usage section but you could prompt for fingerprint before decrypting. They're separate methods so you could change the way it's used. 

The idea of separating the credentials methods from the biometrics verification is to not limit this plugin to only being used for login credentials. Let's say the developer is using this plugin only to protect certain notes in a notes app with only biometrics or pin. I wouldn't want to find another biometrics plugin that allows me to only access the biometric api. There's also the case where the developer doesn't want to store credentials locally even if they're encrypted.

**Comment by gbkwiatt** [comment]
it just makes it pointless gimmick for user to feel safe, when the password is not actually safely stored. Biometrics should at least return some key which will allow decrypt/encrypt password. 
The way it;s done makes biometric completely detached from credentials. So I can or not use it in order to get credentials. 
Even Android docs have section on how it should be done 
https://developer.android.com/training/sign-in/biometric-auth

I get that you did it for your own use for your own purpose, but main purpose of biometric is to secure something. But here it does not secure anything, just confirms that it's "you" using the device.
