### ISSUE TITLE
I do not understand how to use this plugin.

### ISSUE THREAD

**Issue by mahen23** [epicshaggy/capacitor-native-biometric#38]
I am able to verify my fingerprints and my face, but how do i get a token that i can use to uniquely identify my fingerprints against a database of tokens ? So that i can identify who actually wants to login. Thanks

**Comment by jonah-butler** [comment]
Can you post some of your code?

It may be a point of confusion, but the workflow we use at my job is like this:

- User opens app
- Native dialog will pop up on login, asking if they want to opt in to native biometrics (if first open)
- If yes, verify identity
- If yes, user continues to login
- Since user agreed to use native biometrics, setCredentials on successful login

As for the tokens, you want to store the username/email and password in the keychain. 

Once you've set the creds, they will be stored and encrypted in the device keychain. So when a user has opted in, it will verify identity, check for creds, and if they're there, get Credentials, then use the username/email and password that's returned from the device keychain to validate user on your servers. 

It's kind of quiet on this repo, but if you have questions I can help answer them. I recently spent some time trying to get this to work, and was successful.

**Comment by valdo99** [comment]
@mahen23  what happens if user declines the opt in to native bio?
i the verifyIdentity whens users declines will always show the passocode, i think it should directly bypass this call if user has declined.
