### ISSUE TITLE
FaceID automatically evaluated as authenticated when called second time

### ISSUE THREAD

**Issue by adrianvyskoc** [epicshaggy/capacitor-native-biometric#4]
Hi,
I have a problem with FaceID. When I open the app and use FaceID first time, everything is correct. But when I request FaceID auth again, it is automatically evaluated as authenticated.

**Comment by epicshaggy** [comment]
I've experienced the same thing since about a month ago or so.  I worked on this for a few days.  I looked at apple's documentation and compared my implementation to others and everything seems to be correct.  I thought it had something to do with the iOS version but iOS 14 came out and I still get the same behavior.  It has nothing to do with capacitor because I built a native app and got the same behavior.  If you happen to find out what is causing this please let me know or feel free to submit a pull request.

**Comment by buleglay** [comment]
Hi @epicshaggy,

I found the issue is due to the global declaration of `LAContext`, if you declare it on top of both `isAvailable` and `verifyIdentity`, it will work (I've made a local change in the XCode and verified the fix).

Remove `context` from the class property.

Declare `context` in each method requires local authentication API.
```
@objc func isAvailable(_ call: CAPPluginCall) {
        var error: NSError?
        var obj = JSObject()
        let context = LAContext()
        ...
```

```
@objc func verifyIdentity(_ call: CAPPluginCall){
        var canEvaluateError: NSError?
        let context = LAContext()
        ...
```

**Comment by epicshaggy** [comment]
You're right, awesome!  Thanks @buleglay, I updated the package!
