### ISSUE TITLE
Capacitor app is crashing after updating the plugin to 4.2.0

### ISSUE THREAD

**Issue by 11hasnainali** [epicshaggy/capacitor-native-biometric#97]
I am working on a capacitor 5 app, this plugin was working fine with version 4.1.3 but when I updated this plugin to version 4.1.5 or 4.2.0, when setCredentials is called, the app crashes.

**Comment by chriscastro94** [comment]
same problem, even if I downgrade to 4.1.3 still crash

**Comment by audirev** [comment]
Exactly same problem, hopefully a solution soon

**Comment by dimaborbotko** [comment]
same problem

**Comment by cyrilfr** [comment]
I've the same issue.

**Comment by rluttikhuizen** [comment]
Same issue. Also with Capacitor 4.7.1 and Native Biometric plugin 4.1.3. 

android.security.keystore.StrongBoxUnavailableException: Failed to generate key
Caused by: android.security.KeyStoreException: No StrongBox available (public error code: 12 internal Keystore code: -68)

when calling NativeBiometric.setCredentials
